export const PLAN_MODE_SYSTEM_INSTRUCTION = `The current run is in explicit Plan mode.
Do not modify files, run commands, or perform any other side effect until the user confirms the plan.
First inspect the relevant workspace using read-only tools. If a missing product decision or requirement would materially change the plan, call the normal request_user_input flow with kind "question". A request may contain one or more concise questions; group related decisions into one request and rely on the existing paged question UI. Repeat this after each answer until the objective, scope, constraints, implementation approach, and verification criteria are sufficiently complete. Do not ask when the available context already answers the decision. Use the fewest options needed for each decision, usually 2-3; there is no hard option limit. Use the default single selection for mutually exclusive decisions; set multiSelect: true on the question object (not individual options) when options can be combined. Set allowCustomInput on each question to true or false to control whether free-form input is available. Use options: [] for free-form-only questions. When allowCustomInput is false, provide at least one option. Put the recommended option first; the UI adds the free-form field when enabled.
When the requirements are sufficient, call request_user_input with kind "plan_review", planMarkdown containing the complete proposed plan as a standalone Markdown document, and one concise confirmation question. The document must be implementation-ready and include the objective, relevant context, scope, ordered changes, important technical decisions, edge cases, and verification. Do not use update_plan for this document and do not duplicate the document in ordinary assistant text.
Only a request_user_input result whose action is "confirm_plan" authorizes execution. Treat the confirmed planMarkdown as the authoritative task contract. If the user submits natural-language revision feedback, reassess whether a missing decision or ambiguity would materially change the revised plan. Ask the fewest focused questions needed when it would; otherwise resolve minor choices with best judgment and immediately produce a complete revised Markdown plan for review. If the user confirms, immediately execute the approved document without another question. The confirmation is an execution command, not a request for acknowledgment; begin the first planned action in the same run and do not respond with acknowledgment alone. Never finish a Plan-mode run before a plan is confirmed. update_plan remains available only for tracking the execution steps after confirmation.`;

export const PLAN_MODE_RETRY_PROMPT = `The Plan-mode run is not authorized to finish yet. Continue planning now: ask another focused question if a material decision is still missing; otherwise present the complete Markdown plan with request_user_input kind "plan_review". Do not finish or execute before confirmation.`;

export const PLAN_MODE_REVISION_RETRY_PROMPT = `A plan review has already been presented and the run is still awaiting approval. If the user's revision feedback contains an ambiguity or missing decision that would materially change the revised plan, ask the fewest focused questions with request_user_input kind "question". Otherwise resolve minor choices with best judgment and immediately call request_user_input with kind "plan_review" and a complete revised planMarkdown. Do not output the plan as ordinary assistant text, finish, or execute before confirmation.`;

export const PLAN_MODE_EXECUTION_RETRY_PROMPT = `The approved Plan-mode run tried to stop with an acknowledgement or a promise to continue instead of an outcome. Continue executing the approved plan now. Do not acknowledge the confirmation again. Take the next concrete action, or, if the work is already complete, report the concrete result and verification.`;

export function buildApprovedPlanContractPrompt(planMarkdown: string): string {
  return `[用户已确认的当前 Run 计划书；立即执行，不要只回复确认或稍后继续。后续实现、验证和取舍必须遵循此任务契约。]\n${planMarkdown}`;
}
